// Custom Processes editor — the "Custom Processes" tab inside
// `SettingsDialog`. Lets users add/edit/delete the user-defined launchers
// that show up in the tab context menu's Launch submenu.
//
// `CustomProcessDef`s live in `AppConfig.customProcesses`; this tab edits
// that list as a whole and pushes the trimmed result through `configSet`
// when the user clicks Save. Built-in seeded defs (`shell`, `open-folder`,
// `vscode`) are editable like any other entry — Phase 1 chose not to
// special-case them after seeding.
//
// Validation mirrors `validate_custom_processes` in
// `src-tauri/src/config_store.rs` so users see the same rules the backend
// enforces, before the round-trip:
//   * id matches /^[a-zA-Z0-9_-]+$/
//   * trimmed name + command non-empty
//   * ids unique across the list
//
// `id` is used as the wire key and the React `key`, so it is locked once
// the def has been persisted (otherwise an edit would silently change
// what `lastOpenSubSessions` records refer to). New (unsaved) rows allow
// id editing and the row is keyed by a synthetic monotonic counter
// (`__draft-N`) generated by `makeRowKey()` until the user saves; on
// save the row's React key transitions to the persisted `id`.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { selectCustomProcesses, useConfigStore } from '@/store/config-store';
import type { CustomProcessDef, CustomProcessKind } from '@/types/arborist';

export interface CustomProcessesTabProps {
  onClose: () => void;
}

interface DraftRow {
  /** Stable React key. For persisted rows this equals `def.id`; for
   *  unsaved rows it's a synthetic `__draft-N` counter from
   *  `makeRowKey()` so two unsaved rows never collide. */
  rowKey: string;
  /** True iff this row was loaded from the persisted config; locks `id`. */
  persisted: boolean;
  id: string;
  name: string;
  kind: CustomProcessKind;
  command: string;
  enabled: boolean;
  /** Preserved across edits so we don't drop the optional icon hint when
   *  saving. The UI doesn't expose icon editing in v1. */
  icon?: string;
}

const ID_RE = /^[a-zA-Z0-9_-]+$/;

function defToDraft(def: CustomProcessDef): DraftRow {
  const draft: DraftRow = {
    rowKey: def.id,
    persisted: true,
    id: def.id,
    name: def.name,
    kind: def.kind,
    command: def.command,
    enabled: def.enabled,
  };
  if (def.icon !== undefined) draft.icon = def.icon;
  return draft;
}

function draftToDef(row: DraftRow): CustomProcessDef {
  const def: CustomProcessDef = {
    id: row.id.trim(),
    name: row.name.trim(),
    kind: row.kind,
    command: row.command.trim(),
    enabled: row.enabled,
  };
  if (row.icon !== undefined) def.icon = row.icon;
  return def;
}

interface RowError {
  id?: string;
  name?: string;
  command?: string;
}

function validateRow(row: DraftRow, allRows: DraftRow[]): RowError {
  const err: RowError = {};
  const trimmedId = row.id.trim();
  if (trimmedId.length === 0) {
    err.id = 'ID is required';
  } else if (!ID_RE.test(trimmedId)) {
    err.id = 'ID must match [a-zA-Z0-9_-]+';
  } else {
    const dupe = allRows.some((other) => other !== row && other.id.trim() === trimmedId);
    if (dupe) err.id = 'ID must be unique';
  }
  if (row.name.trim().length === 0) err.name = 'Name is required';
  if (row.command.trim().length === 0) err.command = 'Command is required';
  return err;
}

function rowsEqual(a: readonly DraftRow[], b: readonly DraftRow[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    const x = a[i]!;
    const y = b[i]!;
    if (
      x.id !== y.id ||
      x.name !== y.name ||
      x.kind !== y.kind ||
      x.command !== y.command ||
      x.enabled !== y.enabled ||
      x.icon !== y.icon ||
      x.persisted !== y.persisted
    ) {
      return false;
    }
  }
  return true;
}

let nextSyntheticKey = 0;
function makeRowKey(): string {
  nextSyntheticKey += 1;
  return `__draft-${nextSyntheticKey}`;
}

export function CustomProcessesTab({ onClose }: CustomProcessesTabProps): JSX.Element {
  const persistedDefs = useConfigStore(selectCustomProcesses);
  const setConfig = useConfigStore((s) => s.set);

  // Local edit buffer. Initialised from the persisted list and re-synced
  // whenever the persisted snapshot identity changes *and* we have no
  // unsaved edits — this protects the user from losing in-flight work if
  // an unrelated `configSet` (e.g. workspace switch) lands while the tab
  // is open, while still picking up the post-save canonical shape.
  const initialDrafts = useMemo(() => persistedDefs.map(defToDraft), [persistedDefs]);
  const [rows, setRows] = useState<DraftRow[]>(initialDrafts);
  const lastSyncedRef = useRef<DraftRow[]>(initialDrafts);

  useEffect(() => {
    if (rowsEqual(rows, lastSyncedRef.current)) {
      // No unsaved edits — adopt the new persisted snapshot.
      const next = persistedDefs.map(defToDraft);
      setRows(next);
      lastSyncedRef.current = next;
    }
    // We intentionally skip `rows` here: we only want to react when the
    // *persisted* list changes, not when the user is typing.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [persistedDefs]);

  const [saving, setSaving] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const errors = useMemo(() => rows.map((row) => validateRow(row, rows)), [rows]);
  const hasErrors = errors.some((e) => e.id || e.name || e.command);
  const dirty = !rowsEqual(rows, lastSyncedRef.current);

  const updateRow = useCallback((rowKey: string, patch: Partial<DraftRow>): void => {
    setSubmitError(null);
    setRows((prev) => prev.map((row) => (row.rowKey === rowKey ? { ...row, ...patch } : row)));
  }, []);

  const deleteRow = useCallback((rowKey: string): void => {
    setSubmitError(null);
    setRows((prev) => prev.filter((row) => row.rowKey !== rowKey));
  }, []);

  const addRow = useCallback((): void => {
    setSubmitError(null);
    setRows((prev) => [
      ...prev,
      {
        rowKey: makeRowKey(),
        persisted: false,
        id: '',
        name: '',
        kind: 'terminal',
        command: '',
        enabled: true,
      },
    ]);
  }, []);

  const handleSave = useCallback(async (): Promise<void> => {
    if (hasErrors) return;
    setSubmitError(null);
    setSaving(true);
    try {
      const trimmed = rows.map(draftToDef);
      await setConfig({ customProcesses: trimmed });
      onClose();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setSubmitError(message);
    } finally {
      setSaving(false);
    }
  }, [hasErrors, rows, onClose, setConfig]);

  return (
    <div data-testid="custom-processes-tab" className="flex min-h-0 flex-1 flex-col">
      <p className="mb-3 text-xs text-slate-500 dark:text-slate-400">
        Define launchers shown in a session tab’s right-click menu. Terminal launchers run inside a
        sub-tab; application launchers spawn external GUI processes.
      </p>

      <div className="-mx-1 flex-1 space-y-3 overflow-y-auto px-1">
        {rows.length === 0 ? (
          <p
            data-testid="custom-processes-empty"
            className="rounded border border-dashed border-slate-300 px-3 py-4 text-center text-xs text-slate-500 dark:border-slate-700 dark:text-slate-400"
          >
            No custom processes yet.
          </p>
        ) : (
          rows.map((row, idx) => {
            const rowErr = errors[idx]!;
            return (
              <fieldset
                key={row.rowKey}
                data-testid={`custom-process-row-${row.persisted ? row.id : row.rowKey}`}
                className="rounded border border-slate-200 bg-slate-50 p-2 dark:border-slate-700 dark:bg-slate-800"
              >
                <legend className="px-1 text-[11px] font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">
                  {row.persisted ? row.id : 'New launcher'}
                </legend>

                <div className="grid grid-cols-2 gap-2">
                  <label className="block text-xs">
                    <span className="mb-0.5 block text-slate-500 dark:text-slate-400">ID</span>
                    <input
                      type="text"
                      value={row.id}
                      readOnly={row.persisted}
                      aria-label={`ID for ${row.name || row.id || 'new launcher'}`}
                      onChange={(e) => updateRow(row.rowKey, { id: e.target.value })}
                      className="w-full rounded border border-slate-300 bg-white px-2 py-1 font-mono text-xs read-only:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:read-only:bg-slate-800"
                    />
                    {rowErr.id ? (
                      <span
                        role="alert"
                        className="mt-0.5 block text-[11px] text-red-600 dark:text-red-400"
                      >
                        {rowErr.id}
                      </span>
                    ) : null}
                  </label>

                  <label className="block text-xs">
                    <span className="mb-0.5 block text-slate-500 dark:text-slate-400">Name</span>
                    <input
                      type="text"
                      value={row.name}
                      aria-label={`Name for ${row.id || 'new launcher'}`}
                      onChange={(e) => updateRow(row.rowKey, { name: e.target.value })}
                      className="w-full rounded border border-slate-300 bg-white px-2 py-1 text-xs dark:border-slate-700 dark:bg-slate-900"
                    />
                    {rowErr.name ? (
                      <span
                        role="alert"
                        className="mt-0.5 block text-[11px] text-red-600 dark:text-red-400"
                      >
                        {rowErr.name}
                      </span>
                    ) : null}
                  </label>

                  <label className="block text-xs">
                    <span className="mb-0.5 block text-slate-500 dark:text-slate-400">Kind</span>
                    <select
                      value={row.kind}
                      aria-label={`Kind for ${row.id || row.name || 'new launcher'}`}
                      onChange={(e) =>
                        updateRow(row.rowKey, { kind: e.target.value as CustomProcessKind })
                      }
                      className="w-full rounded border border-slate-300 bg-white px-2 py-1 text-xs dark:border-slate-700 dark:bg-slate-900"
                    >
                      <option value="terminal">Terminal (in-app PTY)</option>
                      <option value="application">Application (external GUI)</option>
                    </select>
                  </label>

                  <label className="flex items-center gap-2 self-end pb-1 text-xs">
                    <input
                      type="checkbox"
                      checked={row.enabled}
                      aria-label={`Enabled: ${row.id || row.name || 'new launcher'}`}
                      onChange={(e) => updateRow(row.rowKey, { enabled: e.target.checked })}
                    />
                    <span>Enabled (shown in Launch menu)</span>
                  </label>

                  <label className="col-span-2 block text-xs">
                    <span className="mb-0.5 block text-slate-500 dark:text-slate-400">Command</span>
                    <input
                      type="text"
                      value={row.command}
                      aria-label={`Command for ${row.id || row.name || 'new launcher'}`}
                      onChange={(e) => updateRow(row.rowKey, { command: e.target.value })}
                      className="w-full rounded border border-slate-300 bg-white px-2 py-1 font-mono text-xs dark:border-slate-700 dark:bg-slate-900"
                    />
                    {rowErr.command ? (
                      <span
                        role="alert"
                        className="mt-0.5 block text-[11px] text-red-600 dark:text-red-400"
                      >
                        {rowErr.command}
                      </span>
                    ) : null}
                  </label>
                </div>

                <div className="mt-2 flex justify-end">
                  <button
                    type="button"
                    onClick={() => deleteRow(row.rowKey)}
                    aria-label={`Delete ${row.id || row.name || 'new launcher'}`}
                    className="rounded border border-red-300 bg-white px-2 py-0.5 text-[11px] text-red-700 hover:bg-red-50 dark:border-red-800 dark:bg-slate-900 dark:text-red-300 dark:hover:bg-red-950"
                  >
                    Delete
                  </button>
                </div>
              </fieldset>
            );
          })
        )}
      </div>

      <div className="mt-3 flex items-center gap-2">
        <button
          type="button"
          onClick={addRow}
          data-testid="custom-processes-add"
          className="rounded border border-slate-300 bg-white px-2 py-1 text-xs hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-800 dark:hover:bg-slate-700"
        >
          + Add custom process
        </button>
      </div>

      {submitError && (
        <p
          role="alert"
          data-testid="settings-error"
          className="mt-3 rounded border border-red-300 bg-red-50 px-2 py-1 text-xs text-red-800 dark:border-red-800 dark:bg-red-950 dark:text-red-200"
        >
          {submitError}
        </p>
      )}

      <div className="mt-3 flex justify-end gap-2">
        <button
          type="button"
          onClick={onClose}
          disabled={saving}
          className="rounded border border-slate-300 bg-white px-3 py-1 text-xs hover:bg-slate-100 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800 dark:hover:bg-slate-700"
        >
          Cancel
        </button>
        <button
          type="button"
          onClick={() => void handleSave()}
          disabled={!dirty || hasErrors || saving}
          data-testid="custom-processes-save"
          className="rounded bg-blue-600 px-3 py-1 text-xs font-medium text-white hover:bg-blue-500 disabled:opacity-50"
        >
          {saving ? 'Saving…' : 'Save'}
        </button>
      </div>
    </div>
  );
}
